name: Python application 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-0 \               
          libdbus-glib-1-2 \        
          wget \
          gnupg \
          # Установка Microsoft Edge
          && wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /usr/share/keyrings/microsoft.gpg \
          && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/edge stable main" | sudo tee /etc/apt/sources.list.d/microsoft-edge.list \
          && sudo apt-get update \
          && sudo apt-get install -y chromium-browser microsoft-edge-stable

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install pytest
        pip install allure-pytest
        pip install selenium
        pip install webdriver-manager
        pip install python-dotenv
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Set environment variables
      env:
        DISCORD_EMAIL: ${{ secrets.DISCORD_EMAIL }}
        DISCORD_PASSWORD: ${{ secrets.DISCORD_PASSWORD }}
      run: echo "Environment variables set"

    - name: Test with pytest
      run: |
        pytest test_DiscordFrontEnd.py --alluredir=allure-results
      continue-on-error: true
 
    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
